export const dummyData = [
  {
    id: 1,
    date: "26-Aug-2025",
    role: "react developer",
    company: "Sys-soft",
    email: "syssoft@mail.com",
    mobile: "7708554421",
    from: "Naukri",
    status: "applied",
  },
  {
    id: 2,
    date: "26-Aug-2025",
    role: "react developer",
    company: "Sys-soft",
    email: "syssoft@mail.com",
    mobile: "7708554421",
    from: "Naukri",
    status: "responsed",
  },
  {
    id: 3,
    date: "26-Aug-2025",
    role: "react developer",
    company: "Sys-soft",
    email: "syssoft@mail.com",
    mobile: "",
    from: "Naukri",
    status: "pending",
  },
  {
    id: 4,
    date: "26-Aug-2025",
    role: "react developer",
    company: "Sys-soft",
    email: "syssoft@mail.com",
    mobile: "7708554421",
    from: "Naukri",
    status: "applied",
  },
  {
    id: 5,
    date: "26-Aug-2025",
    role: "react developer",
    company: "Sys-soft",
    email: "syssoft@mail.com",
    mobile: "7708554421",
    from: "Naukri",
    status: "applied",
  },
  {
    id: 6,
    date: "26-Aug-2025",
    role: "react developer",
    company: "Sys-soft",
    email: "syssoft@mail.com",
    mobile: "7708554421",
    from: "Naukri",
    status: "pending",
  },
  {
    id: 7,
    date: "26-Aug-2025",
    role: "react developer",
    company: "Sys-soft",
    email: "syssoft@mail.com",
    mobile: "7708554421",
    from: "Naukri",
    status: "applied",
  },
  {
    id: 8,
    date: "26-Aug-2025",
    role: "react developer",
    company: "Sys-soft",
    email: "syssoft@mail.com",
    mobile: "7708554421",
    from: "Naukri",
    status: "pending",
  },
  {
    id: 9,
    date: "26-Aug-2025",
    role: "react developer",
    company: "Sys-soft",
    email: "syssoft@mail.com",
    mobile: "7708554421",
    from: "LinkedIn",
    status: "responsed",
  },
  {
    id: 10,
    date: "26-Aug-2025",
    role: "react developer",
    company: "Sys-soft",
    email: "syssoft@mail.com",
    mobile: "7708554421",
    from: "Naukri",
    status: "pending",
  },
  {
    id: 11,
    date: "26-Aug-2025",
    role: "react developer",
    company: "Sys-soft",
    email: "syssoft@mail.com",
    mobile: "7708554421",
    from: "Naukri",
    status: "pending",
  },
];
